### ISSUE TITLE
Add issue template to all assignments 

### ISSUE THREAD

**Issue by OlivierJM** [BongoHive/how-to-instructions#3]
I added an issue template to the internship-program repo for the following reasons:
- To make sure users don’t just ask any questions.
- To quickly understand the users query.
- To auto-assign the instructors so that they can quickly see the question raised on any issue, this also auto labels the issue as question.

This issue template needs to be added to all starter code since we don’t where issues will be created. 

**How**
To easily do this, check the GitHub directory in the internship-program repo and you can copy and paste it there or you can create your own issue template and change few things there.
Feel free to reach out for help.

**Comment by Joebbrien** [comment]
Been seeing the raised issues. Makes it easier to resolve

**Comment by alfeyo** [comment]
Ture

**Comment by OlivierJM** [comment]
let me quickly set this up.

**Comment by OlivierJM** [comment]
I have added issue template to all assignments, make sure you double if it is working on all of them.
I am closing this issue.
